[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
#transition = 0.2
storymode = false
storymodemethod = 1
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0
channel_name = "Reddit Tales"

[settings.background]
background_video = "minecraft"
background_audio = "lofi"
background_audio_volume = 0.15
enable_extra_audio = false
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "elevenlabs"
random_voice = false
elevenlabs_voice_name = "Bella"
elevenlabs_api_key = sk_a1766452eccd3575b9957df4005b03cd0f207f5531822b5b
silence_duration = 0.3
no_emojis = false

[text_input]
file_path = "input/story.txt"
subtitle_font = "Arial"
subtitle_size = 24
subtitle_color = "white"
subtitle_outline = 2
